channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.10.12
  - robocorp-truststore=0.8.0
  - pip=23.2.1
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    - rpaframework==27.5.0 # https://rpaframework.org/releasenotes.html
